spring:
  application:
    name: rate-limiter
  cloud:
    sentinel:
      # 取消Sentinel控制台懒加载
      eager: true
      transport:
        dashboard: localhost:10002       log:
        dir: c:/logs/csp/${spring.application.name}        switch-pid: true
server:
  port: 10001